ngsild_to_ros2_client:
    ros__parameters:
      client: 
        host: "localhost"
        port: 1026
      subscription:
        frequency: 2.0
        list: "CommandMessage:9ead8385-80b2-4299-a5b2-81bc6c89be24-id"